# Generated by Django 3.2.8 on 2021-11-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_table_name', models.CharField(max_length=50, verbose_name='tableName')),
                ('category_name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('sub_categories', models.JSONField(default='[]', verbose_name='subCategories')),
            ],
        ),
    ]
