# Generated by Django 3.2.8 on 2021-11-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sub_categories',
            field=models.JSONField(default={'subs': '[]'}, verbose_name='subCategories'),
        ),
    ]
